In [19]:
import numpy as np

In [3]:
arr=np.array([1,2,3,4,5,6])

In [4]:
type(arr)

numpy.ndarray

In [6]:
np_arr=np.arange(1,10)

In [7]:
print(np_arr)

[1 2 3 4 5 6 7 8 9]


In [8]:
l1=[]
for i in range(100):
    l1.append(i)
np_arr=np.arange(100)
print(l1)
print(np_arr)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [10]:
l2=[]
for i in l1:
    l2.append(i*5)

In [12]:
np_arr*5

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220, 225, 230, 235, 240, 245, 250, 255,
       260, 265, 270, 275, 280, 285, 290, 295, 300, 305, 310, 315, 320,
       325, 330, 335, 340, 345, 350, 355, 360, 365, 370, 375, 380, 385,
       390, 395, 400, 405, 410, 415, 420, 425, 430, 435, 440, 445, 450,
       455, 460, 465, 470, 475, 480, 485, 490, 495])

In [24]:
np_arr.size

100

In [23]:
print(np_arr.itemsize)
print(np_arr.itemsize*np_arr.size)

4
400


In [25]:
import sys
print(sys.getsizeof(l1[0]))
print(sys.getsizeof(l1[0])*len(l1))

28
2800


In [27]:
a1=[1,2,3,4]
b1=[1,2,3,4]
 

In [28]:
l_c=[]
for i in range(len(a1)):
    l_c.append(a1[i]+b1[i])

In [30]:
l_c

[2, 4, 6, 8]

In [31]:
a1+b1

[1, 2, 3, 4, 1, 2, 3, 4]

In [33]:
a1=np.array([1,2,3,4])
b1=np.array([1,2,3,4])
a1+b1

array([2, 4, 6, 8])

In [34]:
import time
size=10000

def time_using_list():
    t1=time.time()
    a=list(range(size))
    b=list(range(size))
    c=[a[i]+ b[i] for i in range(size)]
    t2=time.time()
    return (t2-t1)

def time_using_numpy_arr():
    t1=time.time()
    a=np.arange(size)
    b=np.arange(size)
    c=a+b
    t2=time.time()
    return (t2-t1)

In [35]:
t_list=time_using_list()
t_arr=time_using_numpy_arr()

In [36]:
print("list time ",t_list*1000)
print("arr time ", t_arr*1000)

list time  3.0336380004882812
arr time  1.0106563568115234


In [ ]:
# Memory Efficient
#  Faster 
# Have more functinality than list

In [43]:
import numpy as np

In [44]:
l1=[1,2,3,4,5]
arr=np.array(l1)
print(arr)

[1 2 3 4 5]


In [46]:
print(type(arr))

<class 'numpy.ndarray'>


In [48]:
l1=[1,2,3,"7",True,4,5]
arr=np.array(l1, dtype=int)
print(arr)
print(type(arr))

[1 2 3 7 1 4 5]
<class 'numpy.ndarray'>


In [50]:
l1

[1, 2, 3, '7', True, 4, 5]

In [ ]:
# np.ones()
# np.zeros()
# np.full()
# np.empty()

In [53]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [62]:
np.ones((2,3),dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [64]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [54]:
np.zeros((2,5,3),dtype=int)

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [58]:
np.full((2,5),7)

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]])

In [67]:
np.empty((4,4))

array([[1.31815490e-311, 4.39718425e-322, 0.00000000e+000,
        0.00000000e+000],
       [8.34441742e-308, 1.16095484e-028, 8.89492733e+252,
        1.49435797e+248],
       [8.89492733e+252, 9.26740402e+242, 2.35707505e+257,
        1.89130774e+219],
       [2.03309747e-110, 6.48224637e+170, 3.67145870e+228,
        1.99683578e-052]])

In [ ]:
# arange
# linspace (linear space)

In [97]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [22]:
arr1=np.linspace(1,10,50)

In [23]:
arr1

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [68]:
np.identity(4,dtype=int)

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0],
       [0, 0, 0, 1]])

In [118]:
np.flipud(np.identity(4,dtype=int))

array([[0, 0, 0, 1],
       [0, 0, 1, 0],
       [0, 1, 0, 0],
       [1, 0, 0, 0]])

In [69]:
np.eye(7,6,dtype=int)

array([[1, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0]])

In [77]:
np.random.rand(2,5)

array([[0.57855892, 0.99680377, 0.31264624, 0.11964157, 0.51256725],
       [0.18823172, 0.8873931 , 0.6595476 , 0.27508953, 0.8753029 ]])

In [81]:
arr=np.random.randint(5,10,size=(2,3))

In [82]:
arr

array([[6, 5, 8],
       [7, 8, 5]])

In [83]:
arr.shape

(2, 3)

In [84]:
arr.ndim

2

In [85]:
arr.dtype

dtype('int32')

In [86]:
arr.astype('float')

array([[6., 5., 8.],
       [7., 8., 5.]])

In [88]:
arr2=np.arange(1,10)

In [11]:
arr2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
arr2[2:5]

array([3, 4, 5])

In [90]:
arr2[::2]

array([1, 3, 5, 7, 9])

In [14]:
random_arr=np.random.randint(1,20,(2,3))

In [15]:
random_arr

array([[13, 19,  4],
       [10,  1,  5]])

In [23]:
random_arr[0:1,0:2]

array([[13, 19]])

In [95]:
random_arr=np.random.randint(1,20,(3,3))

In [96]:
random_arr

array([[ 6, 15,  6],
       [ 1, 15, 12],
       [10,  5, 13]])

In [101]:
sliced=random_arr[0:2,1:2]

In [103]:
sliced

array([[15],
       [15]])

In [30]:
random_arr=np.random.randint(1,20,(4,4))

In [31]:
random_arr

array([[11, 14,  6,  5],
       [16,  3,  7, 12],
       [ 5,  9, 16, 14],
       [ 7,  9,  5, 17]])

In [105]:
l1=[1,2,3,4,5,6]
print([i+1 for i in l1])

[2, 3, 4, 5, 6, 7]


In [106]:
arr1=np.arange(1,7)

In [107]:
arr1

array([1, 2, 3, 4, 5, 6])

In [108]:
arr1+1

array([2, 3, 4, 5, 6, 7])

In [110]:
arr2=np.arange(1,7)

In [42]:
arr2

array([1, 2, 3, 4, 5, 6])

In [111]:
arr2+arr1

array([ 2,  4,  6,  8, 10, 12])

In [44]:
arr_2d=np.random.randint(1,10,(3,3))
arr_2d

array([[7, 6, 2],
       [8, 1, 1],
       [8, 7, 2]])

In [116]:
arr_2d_=np.random.randint(1,10,(3,3))
arr_2d_

array([[1, 3, 1],
       [6, 9, 4],
       [9, 1, 3]])

In [117]:
arr_2d_.mean()

4.111111111111111

# Array Manipulation

In [ ]:
# transpose
# reshape
# resize
# flatten

In [119]:
arr_2d_

array([[1, 3, 1],
       [6, 9, 4],
       [9, 1, 3]])

In [120]:
np.transpose(arr_2d_)

array([[1, 6, 9],
       [3, 9, 1],
       [1, 4, 3]])

In [2]:
import numpy as np

In [121]:
arr=np.arange(1,25)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [126]:
reshaped_arr=np.reshape(arr,(8,3))

In [127]:
reshaped_arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

In [9]:
np.reshape(arr,(6,4))

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [129]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [133]:
arr.resize(6,4)

In [134]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [135]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [136]:
arr.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24])

In [138]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [139]:
np.unique(arr,return_counts=True)

(array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1], dtype=int64))

In [71]:
arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  4,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [140]:
arr[(arr>=20) | (arr<10)]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 20, 21, 22, 23, 24])

In [141]:
arr1=np.random.randint(1,10,(2,3))

In [142]:
arr2=np.random.randint(1,10,(2,3))

In [143]:
arr1

array([[8, 3, 6],
       [8, 4, 6]])

In [144]:
arr2

array([[6, 5, 1],
       [9, 4, 3]])

In [148]:
np.divide(arr1,arr2)

array([[1.33333333, 0.6       , 6.        ],
       [0.88888889, 1.        , 2.        ]])

In [149]:
arr1.sort()

In [150]:
arr1

array([[3, 6, 8],
       [4, 6, 8]])

In [154]:
arr1

array([[3, 6, 8],
       [4, 6, 8]])

#<u>**Basic Operations & Functions**</u>
* ### <code>np.add()</code> - Adding two arrays
* ### <code>np.subtract()</code> - Subtracting two arrays
* ### <code>np.multiply()</code> - Multiplying two arrays
* ### <code>np.divide()</code> - Dividing two arrays
* ### <code>np.sum()</code> - Sum of items in an array
* ### <code>np.min()</code> - Minimum of items in an array
* ### <code>np.max()</code> -  Minimum of items in an array
* ### <code>np.mean()</code> - Mean of items in an array
* ### <code>np.sort()</code> - Sorting an array

In [155]:
arr2

array([[6, 5, 1],
       [9, 4, 3]])

In [157]:
np.multiply(arr1,arr2)

array([[18, 30,  8],
       [36, 24, 24]])

In [160]:
np.max(arr1)

8